package org.mybatis.dao;

import org.mybatis.model.Actor;
import org.mybatis.model.Episodes;
import org.mybatis.cdi.Mapper;
import org.mybatis.model.Tvseries;

import java.util.List;

@Mapper
public interface EpisodesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EPISODES
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EPISODES
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    int insert(Episodes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EPISODES
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    Episodes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EPISODES
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    List<Episodes> selectAll();

    List<Episodes> selectByTvSeriesId(Integer id);

    void setActors(List<Actor> actorList);

    List<Actor> selectActorForEpisodes(Integer id);

    Tvseries getTvSeries();

    void setTvseries(Tvseries tvseries);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EPISODES
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    int updateByPrimaryKey(Episodes record);
}