package org.mybatis.model;

import java.util.List;
import java.util.Objects;

public class Actor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACTOR.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACTOR.AGE
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACTOR.LASTNAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ACTOR.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private String name;

    private List<Episodes> episodes;

    public List<Episodes> getEpisodes() {
        return episodes;
    }

    public void setEpisodes(List<Episodes> episodes) {
        this.episodes = episodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACTOR.ID
     *
     * @return the value of PUBLIC.ACTOR.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACTOR.ID
     *
     * @param id the value for PUBLIC.ACTOR.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACTOR.AGE
     *
     * @return the value of PUBLIC.ACTOR.AGE
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACTOR.AGE
     *
     * @param age the value for PUBLIC.ACTOR.AGE
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACTOR.LASTNAME
     *
     * @return the value of PUBLIC.ACTOR.LASTNAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACTOR.LASTNAME
     *
     * @param lastname the value for PUBLIC.ACTOR.LASTNAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ACTOR.NAME
     *
     * @return the value of PUBLIC.ACTOR.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ACTOR.NAME
     *
     * @param name the value for PUBLIC.ACTOR.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        org.mybatis.model.Actor actor = (org.mybatis.model.Actor) o;
        return Objects.equals(id, actor.getId()) &&
                Objects.equals(name, actor.getName());
    }
}