package org.mybatis.model;

import java.util.List;
import java.util.Objects;

public class Episodes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EPISODES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EPISODES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EPISODES.NUMBER
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EPISODES.TVSERIES_ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer tvseriesId;



    public List<Actor> getActors() {
        return actors;
    }

    public void setActors(List<Actor> actors) {
        this.actors = actors;
    }

    private Tvseries tvSeries;

    public Tvseries getTvseries() {
        return tvSeries;
    }

    public void setTvseries(Tvseries tvseries) {
        this.tvSeries = tvseries;
    }

    public Tvseries getTvSeries() {
        return tvSeries;
    }

    public void setTvSeries(Tvseries tvSeries) {
        this.tvSeries = tvSeries;
    }

    private List<Actor> actors;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EPISODES.ID
     *
     * @return the value of PUBLIC.EPISODES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EPISODES.ID
     *
     * @param id the value for PUBLIC.EPISODES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EPISODES.NAME
     *
     * @return the value of PUBLIC.EPISODES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EPISODES.NAME
     *
     * @param name the value for PUBLIC.EPISODES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EPISODES.NUMBER
     *
     * @return the value of PUBLIC.EPISODES.NUMBER
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EPISODES.NUMBER
     *
     * @param number the value for PUBLIC.EPISODES.NUMBER
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EPISODES.TVSERIES_ID
     *
     * @return the value of PUBLIC.EPISODES.TVSERIES_ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getTvseriesId() {
        return tvseriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EPISODES.TVSERIES_ID
     *
     * @param tvseriesId the value for PUBLIC.EPISODES.TVSERIES_ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setTvseriesId(Integer tvseriesId) {
        this.tvseriesId = tvseriesId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        org.mybatis.model.Episodes episodes = (org.mybatis.model.Episodes) o;
        return Objects.equals(id, episodes.getId()) &&
                Objects.equals(name, episodes.getName());
    }
}