package org.mybatis.model;

import org.entities.Episode;

import java.util.List;

public class Tvseries {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVSERIES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TVSERIES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    private String name;

    private List<Episodes> episodes;

    public List<Episodes> getEpisodes(){
        return episodes;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVSERIES.ID
     *
     * @return the value of PUBLIC.TVSERIES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVSERIES.ID
     *
     * @param id the value for PUBLIC.TVSERIES.ID
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TVSERIES.NAME
     *
     * @return the value of PUBLIC.TVSERIES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TVSERIES.NAME
     *
     * @param name the value for PUBLIC.TVSERIES.NAME
     *
     * @mbg.generated Wed Apr 08 19:11:35 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}